#SPDX-License-Identifier: MIT-0
---
# tasks file for 3x_ui_container



### CHECK VARIABLES START ###

#- name: Debug action
#  fail:
#    msg: "action has the wrong meaning"
#  when: action not in ["build_image", "stop_container", "start_container", "delete_image"]

### CHECK VARIABLES END ###


- name: Include defaults
  include_vars:
    file: "{{ role_path }}/defaults/main.yml"

- name: Build, run container
  include_tasks: first_start.yml
  when: action == "build_image"

- name: Stop container
  include_tasks: stop_container.yml
  when: action == "stop_container"

- name: Start container
  include_tasks: start_container.yml
  when: action == "start_container"

- name: Delete image
  include_tasks: delete_image.yml
  when: action == "delete_image"

