- name: Check Docker is installed
  become: true
  ansible.builtin.command:
    cmd: which docker
  register: docker_check
  ignore_errors: true

- name: Docker version?
  ansible.builtin.command:
    cmd: docker --version
  register: docker_version
  ignore_errors: true
  when: docker_check.rc == 0

- name: Debug docker version if Docker is installed
  ansible.builtin.debug:
    msg: "{{ docker_version.stdout }}"
  when: docker_check.rc == 0 and docker_version.rc == 0

- name: Debug docker version if Docker is not installed
  ansible.builtin.debug:
    msg: "Docker not installed"
  when: docker_check.rc != 0
