#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-3x-ui

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: install ca-certificates and curl (required)
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: latest

- name: Create a directory for keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download keyring for docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'



- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    create: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest