#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-3x-ui

- name: Check docker version
  include_tasks: check_docker.yml
  register: docker_check

- name: Install docker if it is not there
  include_tasks: install_docker.yml
  when: docker_check.rc != 0